version: '2'
services:
  ruby:
    container_name: vagrant-direct-port
    hostname: vagrant-direct-port
    build: .
    volumes:
      - './:/usr/src/project'
      - '/srv/ruby/root:/root'
    command: sleep infinity
networks:
  default:
    external:
      name: br0
